export const userRoutes = {
    POST_CREATE_USER_REQUEST: 'POST_CREATE_USER_REQUEST',
    POST_CREATE_USER_RESPONSE: 'POST_CREATE_USER_RESPONSE',
    POST_CREATE_USER_ERROR: 'POST_CREATE_USER_ERROR',

    GET_AUTH_STATUS_REQUEST: 'GET_AUTH_STATUS_REQUEST',
    GET_AUTH_STATUS_RESPONSE: 'GET_AUTH_STATUS_RESPONSE',
    GET_AUTH_STATUS_ERROR: 'GET_AUTH_STATUS_ERROR',

    LOGIN_USER_REQUEST: 'LOGIN_USER_REQUEST',
    LOGIN_USER_RESPONSE: 'LOGIN_USER_RESPONSE',
    LOGIN_USER_ERROR: 'LOGIN_USER_ERROR',

    LOGOUT_USER_REQUEST: 'LOGOUT_USER_REQUEST',
    LOGOUT_USER_RESPONSE: 'LOGOUT_USER_RESPONSE',
    LOGOUT_USER_ERROR: 'LOGOUT_USER_ERROR',

    VERIFY_USER_REQUEST: 'VERIFY_USER_REQUEST',
    VERIFY_USER_RESPONSE: 'VERIFY_USER_RESPONSE',
    VERIFY_USER_ERROR: 'VERIFY_USER_ERROR',

    GET_USER_REQUEST: 'GET_USER_REQUEST',
    GET_USER_RESPONSE: 'GET_USER_RESPONSE',
    GET_USER_ERROR: 'GET_USER_ERROR',

    UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
    UPDATE_USER_RESPONSE: 'UPDATE_USER_RESPONSE',
    UPDATE_USER_ERROR: 'UPDATE_USER_ERROR',

    GET_USER_ORDER_REQUEST: 'GET_USER_ORDER_REQUEST',
    GET_USER_ORDER_RESPONSE: 'GET_USER_ORDER_RESPONSE',
    GET_USER_ORDER_ERROR: 'GET_USER_ORDER_ERROR',

    POST_CREATE_ORDER_REQUEST: 'POST_CREATE_ORDER_REQUEST',
    POST_CREATE_ORDER_RESPONSE: 'POST_CREATE_ORDER_RESPONSE',
    POST_CREATE_ORDER_ERROR: 'POST_CREATE_ORDER_ERROR',

    GET_USER_CART_REQUEST: 'GET_USER_CART_REQUEST',
    GET_USER_CART_RESPONSE: 'GET_USER_CART_RESPONSE',
    GET_USER_CART_ERROR: 'GET_USER_CART_ERROR',

    POST_USER_CART_REQUEST: 'POST_USER_CART_REQUEST',
    POST_USER_CART_RESPONSE: 'POST_USER_CART_RESPONSE',
    POST_USER_CART_ERROR: 'POST_USER_CART_ERROR',

    DELETE_USER_CART_REQUEST: 'DELETE_USER_CART_REQUEST',
    DELETE_USER_CART_RESPONSE: 'DELETE_USER_CART_RESPONSE',
    DELETE_USER_CART_ERROR: 'DELETE_USER_CART_ERROR',

    UPDATE_USER_CART_ITEM_REQUEST: 'UPDATE_USER_CART_ITEM_REQUEST',
    UPDATE_USER_CART_ITEM_RESPONSE: 'UPDATE_USER_CART_ITEM_RESPONSE',
    UPDATE_USER_CART_ITEM_ERROR: 'UPDATE_USER_CART_ITEM_ERROR',

    DELETE_USER_CART_ITEM_REQUEST: 'DELETE_USER_CART_ITEM_REQUEST',
    DELETE_USER_CART_ITEM_RESPONSE: 'DELETE_USER_CART_ITEM_RESPONSE',
    DELETE_USER_CART_ITEM_ERROR: 'DELETE_USER_CART_ITEM_ERROR',

    GET_USER_WISHLIST_REQUEST: 'GET_USER_WISHLIST_REQUEST',
    GET_USER_WISHLIST_RESPONSE: 'GET_USER_WISHLIST_RESPONSE',
    GET_USER_WISHLIST_ERROR: 'GET_USER_WISHLIST_ERROR',

    MOVE_TO_WISHLIST_REQUEST: 'MOVE_TO_WISHLIST_REQUEST',
    MOVE_TO_WISHLIST_RESPONSE: 'MOVE_TO_WISHLIST_RESPONSE',
    MOVE_TO_WISHLIST_ERROR: 'MOVE_TO_WISHLIST_ERROR',

    DELETE_WHISHLIST_PRODUCT_REQUEST: 'DELETE_WHISHLIST_PRODUCT_REQUEST',
    DELETE_WHISHLIST_PRODUCT_RESPONSE: 'DELETE_WHISHLIST_PRODUCT_RESPONSE',
    DELETE_WHISHLIST_PRODUCT_ERROR: 'DELETE_WHISHLIST_PRODUCT_ERROR',

    GET_USER_SETTINGS_REQUEST: 'GET_USER_SETTINGS_REQUEST',
    GET_USER_SETTINGS_RESPONSE: 'GET_USER_SETTINGS_RESPONSE',
    GET_USER_SETTINGS_ERROR: 'GET_USER_SETTINGS_ERROR',

    POST_USER_SETTINGS_REQUEST: 'POST_USER_SETTINGS_REQUEST',
    POST_USER_SETTINGS_RESPONSE: 'POST_USER_SETTINGS_RESPONSE',
    POST_USER_SETTINGS_ERROR: 'POST_USER_SETTINGS_ERROR',

    GET_USER_PAYMENTS_REQUEST: 'GET_USER_PAYMENTS_REQUEST',
    GET_USER_PAYMENTS_RESPONSE: 'GET_USER_PAYMENTS_RESPONSE',
    GET_USER_PAYMENTS_ERROR: 'GET_USER_PAYMENTS_ERROR',

    ADD_NEW_PAYMENT_REQUEST: 'ADD_NEW_PAYMENT_REQUEST',
    ADD_NEW_PAYMENT_RESPONSE: 'ADD_NEW_PAYMENT_RESPONSE',
    ADD_NEW_PAYMENT_ERROR: 'ADD_NEW_PAYMENT_ERROR',


    UPDATE_USER_PAYMENT_REQUEST: 'UPDATE_USER_PAYMENT_REQUEST',
    UPDATE_USER_PAYMENT_RESPONSE: 'UPDATE_USER_PAYMENT_RESPONSE',
    UPDATE_USER_PAYMENT_ERROR: 'UPDATE_USER_PAYMENT_ERROR',

    DELETE_USER_PAYMENT_REQUEST: 'DELETE_USER_PAYMENT_REQUEST',
    DELETE_USER_PAYMENT_RESPONSE: 'DELETE_USER_PAYMENT_RESPONSE',
    DELETE_USER_PAYMENT_ERROR: 'DELETE_USER_PAYMENT_ERROR',

    GET_USER_ADDRESS_REQUEST: 'GET_USER_ADDRESS_REQUEST',
    GET_USER_ADDRESS_RESPONSE: 'GET_USER_ADDRESS_RESPONSE',
    GET_USER_ADDRESS_ERROR: 'GET_USER_ADDRESS_ERROR',

    ADD_NEW_ADDRESS_REQUEST: 'ADD_NEW_ADDRESS_REQUEST',
    ADD_NEW_ADDRESS_RESPONSE: 'ADD_NEW_ADDRESS_RESPONSE',
    ADD_NEW_ADDRESS_ERROR: 'ADD_NEW_ADDRESS_ERROR',

    UPDATE_USER_ADDRESS_REQUEST: 'UPDATE_USER_ADDRESS_REQUEST',
    UPDATE_USER_ADDRESS_RESPONSE: 'UPDATE_USER_ADDRESS_RESPONSE',
    UPDATE_USER_ADDRESS_ERROR: 'UPDATE_USER_ADDRESS_ERROR',

    DELETE_USER_ADDRESS_REQUEST: 'DELETE_USER_ADDRESS_REQUEST',
    DELETE_USER_ADDRESS_RESPONSE: 'DELETE_USER_ADDRESS_RESPONSE',
    DELETE_USER_ADDRESS_ERROR: 'DELETE_USER_ADDRESS_ERROR',

    SET_DEFAULT_ADDRESS_REQUEST: 'SET_DEFAULT_ADDRESS_REQUEST',
    SET_DEFAULT_ADDRESS_RESPONSE: 'SET_DEFAULT_ADDRESS_RESPONSE',
    SET_DEFAULT_ADDRESS_ERROR: 'SET_DEFAULT_ADDRESS_ERROR',

    UPDATE_USER_MEMBERSHIP_REQUEST: 'UPDATE_USER_MEMBERSHIP_REQUEST',
    UPDATE_USER_MEMBERSHIP_RESPONSE: 'UPDATE_USER_MEMBERSHIP_RESPONSE',
    UPDATE_USER_MEMBERSHIP_ERROR: 'UPDATE_USER_MEMBERSHIP_ERROR',
}

export const productRoutes = {
    GET_PRODUCTS_REQUEST: 'GET_PRODUCTS_REQUEST',
    GET_PRODUCTS_RESPONSE: 'GET_PRODUCTS_RESPONSE',
    GET_PRODUCTS_ERROR: 'GET_PRODUCTS_ERROR',

    GET_PRODUCTS_BY_ID_REQUEST: 'GET_PRODUCTS_BY_ID_REQUEST',
    GET_PRODUCTS_BY_ID_RESPONSE: 'GET_PRODUCTS_BY_ID_RESPONSE',
    GET_PRODUCTS_BY_ID_ERROR: 'GET_PRODUCTS_BY_ID_ERROR',
}